<a href="https://colab.research.google.com/github/lewisnjue/AI/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

this is the start

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


print(torch.__version__)

2.5.0+cu121


In [2]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


IIntorudction to tensors

In [3]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
# get tensoer back as pyton int
scaler.item()

7

In [6]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
#vector.item() # this will ot work becuasse it has 2 element which cannot be conveted to Scaler


In [9]:
vector.shape

torch.Size([2])

In [10]:
scaler.shape

torch.Size([])

In [11]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### RANODM TENSORS

why random tensors ?

ranodm tensors are imporant becuase the way many neural nnetworks leanr is that tehy start with tensors full of rnadom numbers and then adjust those number to better represent the data
` start with randome number -> look at dat - > update ranodm number -> look at data - > update random number

In [26]:
# create a random tensor of size ( 3 , 4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[9.4797e-01, 6.5474e-01, 8.2328e-01, 9.4928e-01],
        [2.6917e-04, 2.6748e-01, 6.6216e-01, 6.8811e-01],
        [7.6843e-02, 7.6712e-01, 6.3481e-01, 7.7128e-01]])

In [27]:
random_tensor.ndim

2

In [28]:
random_tensor.shape

torch.Size([3, 4])

In [29]:
# create a random tesnor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) # height , width , color channel
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [30]:
torch.rand(size=(3,3))

tensor([[0.3029, 0.5846, 0.8822],
        [0.9018, 0.1599, 0.5161],
        [0.9787, 0.2258, 0.6659]])

In [31]:
torch.rand(3,3)

tensor([[0.7437, 0.8217, 0.5606],
        [0.9585, 0.8434, 0.6490],
        [0.4850, 0.1728, 0.9459]])

## zeors and ones

In [32]:
# create a tesnor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
#create a tenosr of allone
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [35]:
ones.dtype

torch.float32

In [36]:
random_tensor.dtype

torch.float32

In [45]:
## creating a range of tensors and tesnors-like
# use toruch.range()
one_to_ten = torch.arange(start=0,end=11,step = 1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
# creaitng tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## tensor datatypes
**note** tensor datatype is one of the 3 big error your un into with pytorch
and deep leairng :
1. tensor not right dat tpe
2. tenosor nto right shape
3. tensor not right device

In [57]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],

                               dtype=None, # says what is the dtype of the tensor
                               device = None, # it can be cpu , cuda,
                               requires_grad=False) # if you want the pytorch to track the gradient we will look at it later
float_32_tensor

tensor([3., 6., 9.])

In [58]:
float_32_tensor.dtype

torch.float32

In [59]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [60]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [61]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [62]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### getting information from tensors
- tensor not right datatype - to get get `data type from a tensor , canuse ` tensor.dtype` `
- tensor not right shape - to get shape  form a tensor , can use ` tensor.shape`
- tensors not on the right device  - to get device from a tensor can use ` tensor.device`

In [63]:
# crate a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2801, 0.8390, 0.0022, 0.2213],
        [0.5768, 0.7842, 0.5223, 0.3216],
        [0.7854, 0.2472, 0.0194, 0.1409]])

In [64]:
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device of tensor : {some_tensor.device} " )

Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device of tensor : cpu 


In [66]:
some_tensor.ndim

2

### manipulating tenosrs ( tensor operations)
tenosr opeariosn include  
- addition
- subtracion
- multiplicaion ( element wise )
- division
- matrix multiplicaion

In [68]:
# create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10 # this is changing the shape

tensor([11, 12, 13])

In [69]:
tensor * 10

tensor([10, 20, 30])

In [70]:
tensor.ndim

1

In [71]:
tensor - 10

tensor([-9, -8, -7])

In [72]:
# try out pytorch inbuilt fuctions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [73]:
torch.add(tensor,10)

tensor([11, 12, 13])

### metrics multiplicaion

two ways to performing multipliaon in nerual networks and deepleanring
1. element wise multiplicaion
2. matrix multpliaion ( dot product)

In [76]:
# Element wise multipliaion
print(tensor, "*", tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [77]:
# Matrix multiplcaion
torch.matmul(tensor,tensor)

tensor(14)

In [78]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 4.07 ms, sys: 0 ns, total: 4.07 ms
Wall time: 10 ms


In [79]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.5 ms, sys: 0 ns, total: 1.5 ms
Wall time: 5.07 ms


tensor(14)

one of the most common erros is deep learing is shape errors ,
there are two main rules that performing matrix multpliaion needs to satisfy:
1. inner dimmension must match  
* `(3,2) @ ( 3,2 ) ` wont work
* `(2,3) @ ( 3,2 ) ` will work
* `(3,2) @ ( 2,3)` will work

2. the resulting matrix has the shape of the **outer dimensions**
* `(2,3) @ (3,2)`  -> `(2,2)`


In [86]:
torch.rand(3,2) @ torch.rand(2,6) # what matters is the inner dimension


tensor([[0.6976, 0.4737, 0.4101, 0.5823, 0.9219, 0.5520],
        [0.1927, 0.1825, 0.0704, 0.1804, 0.2776, 0.1799],
        [0.5798, 0.4935, 0.2579, 0.5218, 0.8105, 0.5119]])

In [89]:
# shapes for matrix mutplicaion
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#torch.matmul(tensor_A,tensor_B) # this will not work  the inner dimension dont match
torch.mm(tensor_A,tensor_B)
# torch.mm is the same as torch.matmul which is very interesnting becuase we also have @ for the same


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

tto fix our tensor shape , usseus we can manipulat ehs shape of one of the tensor using tranpose
**Transpose** switches the axis or dimensinas of a given tensor

In [94]:
tensor_B = tensor_B.T
tensor_B.shape

torch.Size([3, 2])

In [97]:
tensor_B.T @ tensor_A # This has solved the problem

tensor([[ 76, 100],
        [103, 136]])

### finding the min, max , mean and sum of tensors etc ( tensor aggregation )
these are called tensor agregation dont forget that


In [98]:
# create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [99]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [100]:
# find the max
torch.max(x), x.max()


(tensor(90), tensor(90))

In [101]:
# find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [102]:
# find the mean - note : he toruch.mean( ) requesr a tesore of float 32 datatypes to work



In [103]:
# find teh sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### finding the positional mix max fo tensors
