<a href="https://colab.research.google.com/github/lewisnjue/AI/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

this is the start

In [87]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


print(torch.__version__)

2.5.1+cu124


In [88]:
!nvidia-smi


/usr/bin/sh: 1: nvidia-smi: not found


IIntorudction to tensors

In [89]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [90]:
scaler.ndim

0

In [91]:
# get tensoer back as pyton int
scaler.item()

7

In [92]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [93]:
vector.ndim

1

In [94]:
#vector.item() # this will ot work becuasse it has 2 element which cannot be conveted to Scaler


In [95]:
vector.shape

torch.Size([2])

In [96]:
scaler.shape

torch.Size([])

In [97]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [98]:
MATRIX.ndim

2

In [99]:
MATRIX[0]

tensor([7, 8])

In [100]:
MATRIX[1]

tensor([ 9, 10])

In [101]:
MATRIX.shape

torch.Size([2, 2])

In [102]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [103]:
TENSOR.ndim

3

In [104]:
TENSOR.shape

torch.Size([1, 3, 3])

In [105]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### RANODM TENSORS

why random tensors ?

ranodm tensors are imporant becuase the way many neural nnetworks leanr is that tehy start with tensors full of rnadom numbers and then adjust those number to better represent the data
` start with randome number -> look at dat - > update ranodm number -> look at data - > update random number

In [106]:
# create a random tensor of size ( 3 , 4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6784, 0.4211, 0.8871, 0.0143],
        [0.4268, 0.7678, 0.4096, 0.6367],
        [0.9257, 0.3913, 0.5732, 0.3619]])

In [107]:
random_tensor.ndim

2

In [108]:
random_tensor.shape

torch.Size([3, 4])

In [109]:
# create a random tesnor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) # height , width , color channel
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [110]:
torch.rand(size=(3,3))

tensor([[0.2036, 0.3635, 0.4374],
        [0.4698, 0.6895, 0.0845],
        [0.0708, 0.1401, 0.6322]])

In [111]:
torch.rand(3,3)

tensor([[0.1700, 0.6534, 0.2654],
        [0.3072, 0.6015, 0.3200],
        [0.0446, 0.2580, 0.1326]])

## zeors and ones

In [112]:
# create a tesnor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [113]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [114]:
#create a tenosr of allone
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [115]:
ones.dtype

torch.float32

In [116]:
random_tensor.dtype

torch.float32

In [117]:
## creating a range of tensors and tesnors-like
# use toruch.range()
one_to_ten = torch.arange(start=0,end=11,step = 1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
# creaitng tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [119]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## tensor datatypes
**note** tensor datatype is one of the 3 big error your un into with pytorch
and deep leairng :
1. tensor not right dat tpe
2. tenosor nto right shape
3. tensor not right device

In [120]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],

                               dtype=None, # says what is the dtype of the tensor
                               device = None, # it can be cpu , cuda,
                               requires_grad=False) # if you want the pytorch to track the gradient we will look at it later
float_32_tensor

tensor([3., 6., 9.])

In [121]:
float_32_tensor.dtype

torch.float32

In [122]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [123]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [124]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [125]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### getting information from tensors
- tensor not right datatype - to get get `data type from a tensor , canuse ` tensor.dtype` `
- tensor not right shape - to get shape  form a tensor , can use ` tensor.shape`
- tensors not on the right device  - to get device from a tensor can use ` tensor.device`

In [126]:
# crate a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0965, 0.9572, 0.5609, 0.9701],
        [0.0765, 0.0187, 0.4863, 0.7434],
        [0.9711, 0.0917, 0.2795, 0.8615]])

In [127]:
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device of tensor : {some_tensor.device} " )

Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device of tensor : cpu 


In [128]:
some_tensor.ndim

2

### manipulating tenosrs ( tensor operations)
tenosr opeariosn include  
- addition
- subtracion
- multiplicaion ( element wise )
- division
- matrix multiplicaion

In [129]:
# create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10 # this is changing the shape

tensor([11, 12, 13])

In [130]:
tensor * 10

tensor([10, 20, 30])

In [131]:
tensor.ndim

1

In [132]:
tensor - 10

tensor([-9, -8, -7])

In [133]:
# try out pytorch inbuilt fuctions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [134]:
torch.add(tensor,10)

tensor([11, 12, 13])

### metrics multiplicaion

two ways to performing multipliaon in nerual networks and deepleanring
1. element wise multiplicaion
2. matrix multpliaion ( dot product)

In [135]:
# Element wise multipliaion
print(tensor, "*", tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [136]:
# Matrix multiplcaion
torch.matmul(tensor,tensor)

tensor(14)

In [137]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.14 ms, sys: 0 ns, total: 2.14 ms
Wall time: 1.52 ms


In [138]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 70 μs, sys: 0 ns, total: 70 μs
Wall time: 61 μs


tensor(14)

one of the most common erros is deep learing is shape errors ,
there are two main rules that performing matrix multpliaion needs to satisfy:
1. inner dimmension must match  
* `(3,2) @ ( 3,2 ) ` wont work
* `(2,3) @ ( 3,2 ) ` will work
* `(3,2) @ ( 2,3)` will work

2. the resulting matrix has the shape of the **outer dimensions**
* `(2,3) @ (3,2)`  -> `(2,2)`


In [139]:
torch.rand(3,2) @ torch.rand(2,6) # what matters is the inner dimension


tensor([[0.7884, 0.2933, 0.9248, 0.6521, 1.2694, 0.9433],
        [0.6522, 0.2546, 0.7625, 0.5078, 1.0875, 0.8157],
        [0.2743, 0.0563, 0.3309, 0.3472, 0.2990, 0.1934]])

In [140]:
# shapes for matrix mutplicaion
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#torch.matmul(tensor_A,tensor_B) # this will not work  the inner dimension dont match
#torch.mm(tensor_A,tensor_B)
# torch.mm is the same as torch.matmul which is very interesnting becuase we also have @ for the same


tto fix our tensor shape , usseus we can manipulat ehs shape of one of the tensor using tranpose
**Transpose** switches the axis or dimensinas of a given tensor

In [141]:
tensor_B = tensor_B.T
tensor_B.shape

torch.Size([2, 3])

In [142]:
#tensor_B.T @ tensor_A # This has solved the problem

### finding the min, max , mean and sum of tensors etc ( tensor aggregation )
these are called tensor agregation dont forget that


In [143]:
# create a tensor
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [144]:
# find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [145]:
# find the max
torch.max(x), x.max()


(tensor(91), tensor(91))

In [146]:
# find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [147]:
# find the mean - note : he toruch.mean( ) requesr a tesore of float 32 datatypes to work



In [148]:
# find teh sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### finding the positional mix max fo tensors


In [149]:
x.argmin()

tensor(0)

In [150]:
# find teh posion in tensoer that has the minum valesu with argmin() -> return indexpositon of tage ttesnor where minimu to start
x[x.argmin()] # this is possible interesting

tensor(1)

In [151]:
# find teh position in tensor has the maximun valeus with argmax()
x[x.argmax()]

tensor(91)

## reshaping , stacking , squeezing  and nsqueezing tensors

* reshapping - reshpaes an imput tenosre to a defined shape
* view - return a view fo an input tensor of cetain shape but kepp the same memory as the origin tensor
* stacking - combine multiple tensor on top of each other (vstack ) or horizonatl stack ( hstack)
* squueze - remove all `1` dimenstaions for a tenosr
* unsquueze - add `1` dimenstion to the tensor
* permute - return a view of the input with dimenstions perumuted in a centain way

In [152]:
# lets create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [153]:
# add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [154]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [155]:
# changing z changes x becuase a view of a tensor shares the same memory as teh original input
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [156]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [157]:
# squuze and unsqueeze are useful tensor operaions for manipulating the dimensions foa tensor . ehe a breakdown of how each one works

print(f"Previous tensor : {x_reshaped}")
print(f"Previous shape : {x_reshaped.shape}")

# remove extra dimention from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor : {x_squeezed}")
print(f"New shape : {x_squeezed.shape}")



Previous tensor : tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape : torch.Size([9, 1])

New tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape : torch.Size([9])


In [158]:
# torch.unsqueeze () - add a single dimension to atarget tensor at a specif ic dim ( dimension )
print(f"Previous tensor : {x_squeezed}")
print(f"Previous shape : {x_squeezed.shape}")

# remove extra dimention from x_res
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor : {x_unsqueezed}")
print(f"New shape : {x_unsqueezed.shape}")

Previous tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape : torch.Size([9])

New tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape : torch.Size([1, 9])


In [159]:
# torch.permute - rearrange the dimensions of the tensor in a given order
x_original = torch.rand(size=(224,224,3)) # height , width , color_channesl
print(x_original.size)
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1 , 1->2 , 2->0
print(f"Previous shape : {x_original.shape}")
print(f"New shape : {x_permuted.shape}")


<built-in method size of Tensor object at 0x7f1e06b12ad0>
Previous shape : torch.Size([224, 224, 3])
New shape : torch.Size([3, 224, 224])


In [160]:
x = torch.rand(2,3,5)
x.size()

torch.Size([2, 3, 5])

In [161]:
torch.permute(x,(2,0,1)).size()

torch.Size([5, 2, 3])

In [162]:
# permute is commonly used with images

### selecting data from the tensor


In [163]:
## Indexing ( selecitn dat form tensors)
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [164]:
# Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [165]:
x[0][0]

tensor([1, 2, 3])

In [166]:
# you can use
x[0,0]

tensor([1, 2, 3])

In [167]:
x[0][0][0]

tensor(1)

In [168]:
# you can also your : to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [169]:
# get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])


## pytorch tensors and numpy

numpy is a popular scientific pyton numerical computing library . and becuasoe f this , pytorch has funtionaliry to interact with it .
* data in numpy, want in pytorch tensor  > `torch.from_numpy(ndarray)`
* pytorch tensor -> torch.tensor.numpy()


In [171]:
""" import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor """

' import torch\nimport numpy as np\narray = np.arange(1.0,8.0)\ntensor = torch.from_numpy(array).type(torch.float32)\narray, tensor '

In [172]:
array.dtype

dtype('float64')

In [173]:
torch.arange(1.0,8.0).dtype

torch.float32

In [174]:
# the default from numpy is float64


In [175]:
# tenosr to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

RuntimeError: Numpy is not available

## reproducabilty ( try ing to take random out of random )
in short how a neural network learn
` start with random numers -> tensor operations -> update ranodm numbers to gry and make them better representaions fo the data -> again -> again -> again `

to reuce the randomness in nerual netorks and pytorch comes the comcept of **random seed**
essenstailly what the random seed does is "flavour" and ranodmness.

In [ ]:
import torch
# create tow random tensor
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)
print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.1916, 0.8605, 0.1646, 0.7643],
        [0.2787, 0.9552, 0.0514, 0.2246],
        [0.1116, 0.0084, 0.0457, 0.3331]])
tensor([[0.7783, 0.8224, 0.4628, 0.4599],
        [0.2703, 0.4297, 0.8685, 0.9219],
        [0.6680, 0.6235, 0.8926, 0.4510]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# lets make some random but reproducible tensors
import torch
# set the ranom seed
RANOM_SEED = 42
torch.manual_seed(RANOM_SEED )
random_tensor_c = torch.rand(3,4)
torch.manual_seed(RANOM_SEED )
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## differnt way to accesssing gpu using for tensors
GPU = faster computation on numers , thanks to CUDE + CNVIDIAhadware
### getting a GPU
1. easiest - use google colab for a free GPU  or options to upgrade as well
2. use your own gpu - takes a little bit of setpu and requeres to investmet to purchasing a gpu
3. use cloud computing - AWS , AZURE , these services allow you to rest computer and access them


In [177]:
## check for gpu access pytorch
import torch
torch.cuda.is_available()

False

In [178]:
# setup  device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [179]:
# count number of devices
torch.cuda.device_count()

0

## putting tensors ( and models ) on the gpu
the reason we want our tensors / models on the gpu is because usign a gpu is fast for tensor operation faster than a cpu

In [180]:
# create a tensor
tensor = torch.tensor([1,2,3],device=device)
# tensor on gpu by default is on cpu
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


### moving tenosrs back to the cpu

In [181]:
# if tensor is on gpu cant tranform in to numpy
# tensor.numpy() # this will give an error  -> this is becuase it is on gpu

tensor_back_on_cpu = tensor.cpu().numpy()
tensor_back_on_cpu # this is how we can solve the issue

RuntimeError: Numpy is not available